kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v1
metadata:
  name: myhpacpu
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: webdeployments
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50

